### ISSUE TITLE
`LayoutWrapper` documentation

### ISSUE THREAD

**Issue by NSExceptional** [Azoy/Echo#20]
`LayoutWrapper` appears to be undocumented in the wiki, as well as how to use it. Trying to figure that out myself but you can't submit PRs for wikis

**Comment by Azoy** [comment]
Hey, sorry for being MIA for a few days (vacation), but `LayoutWrapper` is intended to be a private protocol for implementation purposes, but the wiki generator picks up the private conformances as well. If you're interested in what its meant to be:

```swift
public struct PublicStruct: LayoutWrapper {
  typealias Layout = _NonPublicLayoutStruct

  let ptr: UnsafeRawPointer

  var name: String {
    // This is exactly the same as ptr.load(as: _NonPublicLayoutStruct.self)._name
    layout._name
  }

  var age: Int {
    // This is exactly the same as ptr.load(as: _NonPublicLayoutStruct.self)._age
    layout._age
  }
}

struct _NonPublicLayoutStruct {
  let name: String
  let age: Int
}
```

where the idea is that the public struct type stores a pointer to the non public struct that essentially defines the layout of some data type. This has its advantages of being able to keep the pointer to and access array type fields at an offset from the layout struct which aren't really expressible in Swift.

**Comment by NSExceptional** [comment]
Oh, oops! Thanks for the explanation 😄
