### ISSUE TITLE
`container(for:)` sometimes re-boxes the value passed in?

### ISSUE THREAD

**Issue by NSExceptional** [Azoy/Echo#49]
Sometimes when I pass a variable that is already `Any` into `container(for:)`, it gets boxed _again_? Is there a way to avoid this? Why would an existing `Any` need to be re-boxed?

The code in question:

<img width="719" alt="Screenshot 2021-05-05 at 10 34 58 PM" src="https://user-images.githubusercontent.com/8371943/117238249-220e8580-adf2-11eb-878e-4f71b0b4b1d9.png">

The debugger:

<img width="332" alt="Screenshot 2021-05-05 at 10 32 29 PM" src="https://user-images.githubusercontent.com/8371943/117238397-67cb4e00-adf2-11eb-913c-b77de30af635.png">

If we assume `box` is telling the truth—judging by it's `type = Any` ivar—and look at the memory in the first word it stores, we find the contents look eerily similar to the contents of `value`:

<img width="792" alt="Screenshot 2021-05-05 at 10 33 19 PM" src="https://user-images.githubusercontent.com/8371943/117238348-5124f700-adf2-11eb-9d88-346e83e758f0.png">

What's going on here? O_o I don't recall this happening up till now, but I suppose it's possible it has been happening all along without me noticing somehow?

**Comment by NSExceptional** [comment]
I noticed that sometimes, some variables (all typed as `Any`) will show up in the debugger with their respective types, and others will show up as `Any` but with the correct type in the `type` storage, as shown below. i.e. below, `name` and `age` show up as `Any` while the other keys show up as their underlying types; `age` is supposed to be `5` for example

<img width="367" alt="Screenshot 2021-05-06 at 10 36 13 AM" src="https://user-images.githubusercontent.com/8371943/117326048-e78b0400-ae56-11eb-9ab0-2aae58b5e9c8.png">

This seems directly related. What causes this?

**Comment by NSExceptional** [comment]
Modifying the function to work like this has alleviated the issue entirely, though I wonder whether it is something I'm doing wrong or whether this sort of logic is truly necessary?

```swift
public func container(for instance: Any) -> AnyExistentialContainer {
    var box = unsafeBitCast(instance, to: AnyExistentialContainer.self)
    if (box.type == Any.self) {
        return box.projectValue().assumingMemoryBound(to: AnyExistentialContainer.self).pointee
    }
    
    return box
}
```

**Comment by Azoy** [comment]
Thanks for the report! Yeah, I initially thought this might be a case where there was multiple nested containers, and it appears it was the case. I've pushed a commit that should hopefully solve this for you: https://github.com/Azoy/Echo/commit/c93e53d8c26830928283e8bf8c2158501841357d
