### ISSUE TITLE
Accessing name of enum with a raw value

### ISSUE THREAD

**Issue by joshuawright11** [Azoy/Echo#9]
First of all, this library is awesome! Thanks for all your hard work @Azoy.

Was wondering if there was a way to get the name of an enum case (not the raw value) via this library. 

e.g...
```swift
enum Country: String {
    case usa = "united_states_of_america"
    case ca = "canada"

    func caseName() -> String {
        // ??
    }
}

print(Country.usa.rawValue) // prints "united_states_of_america"
print(Country.usa.caseName()) // prints "usa"
```

**Comment by Azoy** [comment]
I believe you can do this by simply:
```swift
String(describing: Country.usa)
```

**Comment by joshuawright11** [comment]
Ah, yes you're right. I didn't check my example before sending it. The use case here is I want to find the name of potentially custom `CodingKey` on a type, and it seems like there is a custom `description` property on `CodingKey` that interferes with the typical description. In the example above, if you conform `Country` to `CodingKey` you end up with...

```swift
enum Country: String, CodingKey {
    case usa = "united_states_of_america"
    case ca = "canada"
}

print(Country.usa.rawValue) // prints "united_states_of_america"
print(String(describing: Country.usa)) // prints "Country(stringValue: "united_states_of_america", intValue: nil)"
```

**Comment by Azoy** [comment]
I see...

My initial reaction is to use something a little complicated in that case then. It might be a little clunky, certainly something that seems worth adding to this library, but here is a little function to get the case name:
```swift
func getEnumCaseName<T>(for value: T) -> String? {
  guard let metadata = reflect(T.self) as? EnumMetadata else {
    return nil
  }

  return withUnsafePointer(to: value) {
    let raw = UnsafeRawPointer($0)
    let tag = Int(metadata.enumVwt.getEnumTag(for: raw))
    return metadata.descriptor.fields.records[tag].name
  }
}

enum Country: String, CodingKey {
  case usa = "united_states_of_america"
  case ca = "canada"
}

print(getEnumCaseName(for: Country.usa)) // usa
```

**Comment by joshuawright11** [comment]
Wow, works perfectly. Thanks @Azoy !

Out of curiosity I noticed you mentioned you & some others are trying to get this library / pieces of this library added to the swift standard library. Any updates on the direction of that?

I ask because I'm including `Echo` in some experimental server stuff I've been doing recently & am curious what the future of it might be / how likely it is this would break in future swift versions.

**Comment by Azoy** [comment]
Yes, we're trying to move some of the reflection keypath APIs into the standard library. We're almost ready to release information!

There are some things that I'm planning on namespacing to make it obvious what APIs could break in the future because they're not ABI stable. Right now that includes all the keypath APIs and tuple/existential/function/metatype metadata. It's also worth noting that if you're deploying on a platform with a non-stable ABI, then other metadata structures can be expected to change as well.

**Comment by joshuawright11** [comment]
Will definitely be looking out for that release. Thanks again for the help!
